apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp:
  labels:
    controller-uid:
    job-name: cron-update-adv-config-cache-test03
  name: cron-update-adv-config-cache-test03
  namespace: micro
  resourceVersion:
  selfLink:
  uid:
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      controller-uid:
  template:
    metadata:
      labels:
        controller-uid:
        job-name: cron-update-adv-config-cache-test03
    spec:
      containers:
        - command:
            - /bookadv-cmd
            - cron_update_adv_config_cache
          env:
            - name: MICRO_ENVIRONMENT
              value: k8s
            - name: RUN_MODE
              value: test
            - name: DEPLOY_TIME
              value: '${DEPLOY_TIME}'
          image: 'registry-vpc.cn-shanghai.aliyuncs.com/7mao_sh/bookadv-cmd:test-1'
          imagePullPolicy: Always
          name: cron-update-adv-config-cache-test03
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /config/test
              name: config-volume
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: regsecret-sh
      restartPolicy: OnFailure
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 420
            name: bookadv
          name: config-volume

status:
  completionTime:
  conditions:
    - lastProbeTime:
      lastTransitionTime:
      status: 'True'
      type:
  startTime:
  succeeded:
