# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-21 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=32)),
                ('weight', models.IntegerField(default=0, max_length=3)),
                ('height', models.CharField(default=0, max_length=3)),
            ],
        ),
    ]
