# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-21 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20190321_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
